
# Cleans up resources left behind that Terraform does not delete. Useful to run when destory-all does not work

#In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild-gke-dev-deploy.yaml --timeout=30m
steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=aws-access-key --format='get(payload.data)' | tr '_-' '/+' | base64 -d > aws-access-key-leftovers.txt" ]
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=aws-secret-access-key --format='get(payload.data)' | tr '_-' '/+' | base64 -d > aws-secret-access-key-leftovers.txt" ]
  - name: gcr.io/${PROJECT_ID}/leftovers
    entrypoint: 'bash'
    args: 
    - '-c'
    - 'echo Running command leftovers --iaas=aws --filter=${_ENVIRONMENT_NAME} --aws-access-key-id==$(cat aws-access-key-leftovers.txt) --aws-secret-access-key=$(cat aws-secret-access-key-leftovers.txt) --no-confirm'
  - name: gcr.io/${PROJECT_ID}/leftovers
    args: ['--iaas=aws','--filter=${_ENVIRONMENT_NAME}','--aws-access-key-id==$(cat aws-access-key-leftovers.txt)', '--aws-secret-access-key=$(cat aws-secret-access-key-leftovers.txt)', '--no-confirm']
substitutions:
  _ENVIRONMENT_NAME: dev
tags: ['cloud-builders-community']
