# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#  Creates EKS Clusters and regiters them with Anthos
#In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild-eks-dev-deploy.yaml --timeout=30m
steps:
  - name: 'gcr.io/${PROJECT_ID}/simple-anthos-build:latest'
    id: '1_vpc'
    entrypoint: 'bash'
    args: ['-c', '/builder/entrypoint.bash run-all apply --terragrunt-non-interactive']
    secretEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']
    env:
      - "TF_IN_AUTOMATION=1"
      - "TF_INPUT=false"
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "PROJECT_ID=${PROJECT_ID}"
      - "ENVIRONMENT_NAME=${_ENVIRONMENT_NAME}" 
    dir: eks-aws/${_AWS_REGION_NAME}/${_ENVIRONMENT_NAME}/1_vpc
  - name: 'gcr.io/${PROJECT_ID}/simple-anthos-build:latest'
    id: '2_eks'
    entrypoint: 'bash'
    args: ['-c', '/builder/entrypoint.bash run-all apply --terragrunt-non-interactive']
    secretEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']
    env:
      - "TF_IN_AUTOMATION=1"
      - "TF_INPUT=false"
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "PROJECT_ID=${PROJECT_ID}"
      - "ENVIRONMENT_NAME=${_ENVIRONMENT_NAME}" 
    dir: eks-aws/${_AWS_REGION_NAME}/${_ENVIRONMENT_NAME}/2_eks
  - name: 'gcr.io/${PROJECT_ID}/simple-anthos-build:latest'
    id: '3_hub'
    entrypoint: 'bash'
    args: ['-c', '/builder/entrypoint.bash run-all apply --terragrunt-non-interactive']
    secretEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']
    env:
      - "TF_IN_AUTOMATION=1"
      - "TF_INPUT=false"
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "PROJECT_ID=${PROJECT_ID}" 
      - "ENVIRONMENT_NAME=${_ENVIRONMENT_NAME}" 
    dir: eks-aws/${_AWS_REGION_NAME}/${_ENVIRONMENT_NAME}/3_hub
  - name: 'gcr.io/${PROJECT_ID}/simple-anthos-build:latest'
    id: '4_hub_login'
    entrypoint: 'bash'
    args: ['-c', '/builder/entrypoint.bash run-all apply --terragrunt-non-interactive']
    secretEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']
    env:
      - "TF_IN_AUTOMATION=1"
      - "TF_INPUT=false"
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "PROJECT_ID=${PROJECT_ID}" 
      - "ENVIRONMENT_NAME=${_ENVIRONMENT_NAME}" 
    dir: eks-aws/${_AWS_REGION_NAME}/${_ENVIRONMENT_NAME}/4_hub_login
  - name: 'gcr.io/${PROJECT_ID}/simple-anthos-build:latest'
    id: '5_acm'
    entrypoint: 'bash'
    args: ['-c', '/builder/entrypoint.bash run-all apply --terragrunt-non-interactive']
    secretEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']
    env:
      - "TF_IN_AUTOMATION=1"
      - "TF_INPUT=false"
      - "TF_VAR_project_id=${PROJECT_ID}"
      - "PROJECT_ID=${PROJECT_ID}"
      - "ENVIRONMENT_NAME=${_ENVIRONMENT_NAME}" 
      - "ACM_REPO=${_ACM_REPO}"
    dir: eks-aws/${_AWS_REGION_NAME}/${_ENVIRONMENT_NAME}/5_acm
# Get AWS secret from Secrets Manager
availableSecrets:
  secretManager:
  - versionName: projects/arau-anthos-seed/secrets/aws_access_key_id/versions/latest
    env: 'AWS_ACCESS_KEY_ID'
  - versionName: projects/arau-anthos-seed/secrets/aws_secret_access_key/versions/latest
    env: 'AWS_SECRET_ACCESS_KEY'
substitutions:
  _ENVIRONMENT_NAME: dev
  _AWS_REGION_NAME: us-east-1
  _ACM_REPO: git@github.com:GoogleCloudPlatform/csp-config-management.git
tags: ['cloud-builders-community']
