apiVersion: v1
kind: ConfigMap
metadata:
  name: whereami-configmap
data:
  BACKEND_ENABLED: "True"
  # when defining the BACKEND_SERVICE using an HTTP protocol, indicate HTTP or HTTPS; if using gRPC, use the host name only
  BACKEND_SERVICE: "http://whereami-backend" # substitute with corresponding service name - this example assumes both services are in the same namespace and is unencrypted HTTP
  METADATA: "frontend"